Update dependencies, repo list. Resolves #24

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,22 +1,8 @@
 #!/usr/bin/env bash
 
-set -o errexit
-set -o pipefail
-
-DC="${DC:-exec}"
-
-# If we're running in CI we need to disable TTY allocation for docker compose
-# commands that enable it by default, such as exec and run.
-TTY=""
-if [[ ! -t 1 ]]; then
-  TTY="-T"
-fi
-
-# -----------------------------------------------------------------------------
-# Helper functions start with _ and aren't listed in this script's help menu.
-# -----------------------------------------------------------------------------
-
-# -----------------------------------------------------------------------------
+set -o errexit  # abort on nonzero exitstatus
+set -o nounset  # abort on unbound variable
+set -o pipefail # don't hide errors within pipes
 
 function cov:test {
   # Run pytest
@@ -50,40 +36,40 @@ function nox:docs {
 
 function nox:lint {
   # Run a number of flake8 linting tests
-  nox -s lint-3.13 "${@}"
+  nox -s lint-3.14 "${@}"
 }
 
 function nox:pyright {
   # Run pyright typing checks
   # cmd nox -s pyright-3.13 "${@}"
-  nox -s pyright-3.13 "${@}"
+  nox -s pyright-3.14 "${@}"
 }
 
 function nox:test {
   # Run several pytest and coverage checks
   # cmd nox -s tests-3.13 "${@}"
-  nox -s tests-3.13 "${@}"
+  nox -s tests-3.14 "${@}"
 }
 
 function nox:tests {
   # Run tests for all currently supported Python versions
-  nox -s tests-3.10 tests-3.11 tests-3.12 tests-3.13 "${@}"
+  nox -s tests-3.12 tests-3.13 tests-3.14 "${@}"
 }
 
 function nox:re-tests {
   # Run tests for all currently supported Python versions
-  nox -rs tests-3.10 tests-3.11 tests-3.12 tests-3.13 "${@}"
+  nox -rs tests-3.12 tests-3.13 tests-3.14 "${@}"
 }
 
 function nox:current {
   # Run code quality tests only for latest supported Python version
-  nox -s lint-3.13 coverage-3.13 safety-3.13 tests-3.13 "${@}"
+  nox -s lint-3.14 coverage-3.14 tests-3.14 "${@}"
 }
 
 function nox:re-current {
   # Run tests only for latest supported Python version
   # DO NOT REBUILD VENVS
-  nox -s lint-3.13 coverage-3.13 safety-3.13 tests-3.13 "${@}"
+  nox -rs lint-3.14 coverage-3.14 tests-3.14 "${@}"
 }
 
 function nox:all {
@@ -140,6 +126,5 @@ function help {
   printf "\nExtended help:\n  Each task has comments for general usage\n"
 }
 
-# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
 TIMEFORMAT=$'\nTask completed in %3lR'
 time "${@:-help}"
